### ISSUE TITLE
funcargs on describe functions

### ISSUE THREAD

**Issue by casimiro** [ropez/pytest-describe#11]
Hey there! First of all, thanks for sharing this plugin. I've been using it in some projects and I really like it. However, there's a feature I'm missing: be able to add funcargs to describe functions;

Consider the following scenario:

```python
def describe_calculate_something_hard(calculator):
    def when_input_is_x(x, expected_result):
        assert calculator.calculate(x) == expected_result
```

If I do this, the `calculator` argument is not handled by the pytest. Maybe I'm just using it wrong.
But if this is a missing feature, I would like to have it. I could even implement it by myself, but some directions would be much appreciated.

Best regards,
casimiro.

**Comment by ropez** [comment]
This has been asked before #9 

The "describe" functions are evaluated in the test collection phase, hence its not possible to access fixtures before the tests start running. It may or may not be possible to implement this with some "magic" where the scope of the outer function is altered before the inner function is called, but I'm not sure.

**Comment by ropez** [comment]
I tried messing around a little bit with the code. I'm pretty sure that it's impossible to "magically" change the local variables of the outer function before running each of the inner functions (see link below for some related discussion).

http://stackoverflow.com/questions/23499042/why-does-modifying-parent-frame-in-python-work-only-for-module-frames

I guess it would be possible to call the describe function one additional time for each test function inside, so that we in practice create a new test function, bound to the funcarg value, just before we invoke it. But that would be too messy, I think. Any code inside the "describe" block would be executed once in the test collection phase, and then once more for each test inside. With nested describe block, it would be a complete chaos.
