### ISSUE TITLE
TypeError: described_as() takes at least 2 arguments (0 given)

### ISSUE THREAD

**Issue by iorlas** [ropez/pytest-describe#7]
Don't know what to say. Here is some info:

    Test session starts (platform: linux2, Python 2.7.8, pytest 2.8.2, pytest-sugar 0.5.1)
    django settings: project.settings (from ini file)
    rootdir: /home/l/projects/contextads, inifile: pytest.ini
    plugins: describe-0.10.2, sugar-0.5.1, django-2.9.1

    ../../.virtualenvs/lc/local/lib/python2.7/site-packages/pytest_describe/plugin.py:76: in _getobj
        return self._memoizedcall('_obj', self._importtestmodule)
    ../../.virtualenvs/lc/local/lib/python2.7/site-packages/_pytest/main.py:317: in _memoizedcall
        res = function()
    ../../.virtualenvs/lc/local/lib/python2.7/site-packages/pytest_describe/plugin.py:84: in _importtestmodule
        module = make_module_from_function(self.funcobj)
    ../../.virtualenvs/lc/local/lib/python2.7/site-packages/pytest_describe/plugin.py:29: in make_module_from_function
        module.__dict__.update(trace_function(funcobj))
    ../../.virtualenvs/lc/local/lib/python2.7/site-packages/pytest_describe/plugin.py:19: in trace_function
        funcobj(*args, **kwargs)
    E   TypeError: described_as() takes at least 2 arguments (0 given)

**Comment by iorlas** [comment]
Oh, thanks, I thought about similar issue, but my code has no similar functions.

But... I use `pyhancrest` package. I discovered that it has described_as `matcher`. And my code imports all matchers by `*` -_-

https://pyhamcrest.readthedocs.org/en/release-1.8/decorator_matchers/#module-hamcrest.core.core.described_as

I'm thinking about the way to detect is it your function or not...

**Comment by ropez** [comment]
I'm going to close this now, since it's not an issue with the plugin. The plugin just does what it's advertised to do; it takes all functions in your module, that starts with "describe" and calls them a certain way.

For the issue that you're having, there are several things you can do:

- Don't use `from X import *`, use `from X import stuff, you, need` instead
- Don't use `from X import`, just use `import X`, and change your code to use `X.stuff` instead of `stuff`
- Keep your code as it it, but define a `__all__` attribute in your module, with a list of functions that you want to be seen by pytest (I haven't actually tried this, but I suppose it should work)

**Comment by iorlas** [comment]
Yea, I know that, fixed it already in my codebase.

Thing, which bothers me is that you blindly took functions by name. This is why I think **it could be issue with this plugin**. But yea, I'll be fine with that.
